name: 🐛 Сообщить об ошибке
description: Создать отчет, чтобы помочь нам улучшить проект
title: "[BUG] <краткое описание проблемы>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время сообщить об ошибке! 
  - type: textarea
    id: what-happened
    attributes:
      label: Что произошло?
      description: Опишите, что именно пошло не так.
      placeholder: Например, кнопка генерации не нажимается...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Как воспроизвести?
      description: Опишите шаги, которые привели к ошибке.
      placeholder: |
        1. Открыть страницу курса
        2. Ввести сумму...
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Окружение
      description: Браузер, ОС.
      placeholder: Chrome на Windows 11
  - type: checkboxes
    id: checks
    attributes:
      label: Проверки
      options:
        - label: Я проверил, что этой ошибки еще нет в списке Issues.
          required: true
